### ISSUE TITLE
ISSUE-2504: bin/bkctl cluster init fails with "java.lang.IllegalArgumentException: No service URI is provided"

### ISSUE THREAD

**Issue by sijie** [streamnative/bookkeeper#280]
Original Issue: apache/bookkeeper#2504 

---

**BUG REPORT**
I am trying to setup a StreamStorage Cluster, but the command to init the cluster is not working.

***Describe the bug***

If you run this command, there is no error and no way to understand what to do (without checking into BK code)

`bin/bkctl cluster init`

```
java.lang.IllegalArgumentException: No service URI is provided
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.apache.bookkeeper.stream.cli.commands.cluster.InitClusterCommand.apply(InitClusterCommand.java:114)
	at org.apache.bookkeeper.stream.cli.commands.cluster.InitClusterCommand.apply(InitClusterCommand.java:53)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:94)
	at org.apache.bookkeeper.tools.common.BKCommand.lambda$apply$0(BKCommand.java:49)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:224)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:51)
	at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:39)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.framework.CliCommandGroup.apply(CliCommandGroup.java:68)
	at org.apache.bookkeeper.tools.framework.Cli.run(Cli.java:232)
	at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:244)
	at org.apache.bookkeeper.tools.cli.BKCtl.main(BKCtl.java:58)
Error : No service URI is provided

```

***Expected behavior***

The command succeedes

***Suggestions***
We should document how to start with the BK Stream Storage Service

**Comment by Jennifer88huang** [comment]
@sijia-w would you like to have a try on this issue?
